//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weather.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Geoname
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Geoname()
        {
            this.Forecasts = new HashSet<Forecast>();
        }
    
        public string toponymName { get; set; }
        public string name { get; set; }
        public string lat { get; set; }
        public string lng { get; set; }
        public string geonameId { get; set; }
        public string countryCode { get; set; }
        public string countryName { get; set; }
        public string fcl { get; set; }
        public string fcode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Forecast> Forecasts { get; set; }
    }
}
